### ISSUE TITLE
Migrate to Vue 3 with Vite

### ISSUE THREAD

**Issue by undergroundwires** [undergroundwires/privacy.sexy#230]
**Vue 2.0** has become obsolete and its continued use, along with its ecosystem (Vue CLI and associated plugins), has begun to pose dependency challenges. Vue 2 support is slated to conclude on December 31st, 2023.

**Vue 3.0**: Vue CLI is now in maintenance mode and Vite is the recommended tools. Official documentation points to [Vue CLI -> Vite Migration Guide from VueSchool.io](https://vueschool.io/articles/vuejs-tutorials/how-to-migrate-from-vue-cli-to-vite/).

 It is now of high importance to modernize our application to Vue 3.0 for seamless maintenance and future modifications. This migration is a task involves several steps and will demand major refactorings in the codebase.

## TODO

- [x] Complete migration to Vue 3.0
  - [x] Eliminate the dependency on `liquor-tree`, which is based on Vue 2.0, enabling #158.
  - [x] Eliminate the dependency on `v-tooltip`, which is also based on Vue 2.0.
  - [x] Eliminate the dependencies on `@fortawesome`, which is also based on Vue 2.0.
  - [x] Eliminate the dependency on `vue-js-modal`, which is also based on Vue 2.0.
  - [x] Refactor all components to use Composition API (`@vue/composition-api` plugin allows doing this while using Vue 2.0).
   - [x] Initiate the migration to Vue 3 by introducing [`@vue/compat`](https://v3-migration.vuejs.org/migration-build.html).
   - [x] String search "Vue 2" and "Vue 3" and fix all hacks.
- [x] Complete migration to Vite
  - [x] Replace mocha & chai with [Vitest](https://vitest.dev/)
  - [x] Remove the webpack dependency to enable the dynamic building and embedding of YAML files, thereby effectively addressing issue #126, or check also [Modyfi/vite-plugin-yaml](https://github.com/Modyfi/vite-plugin-yaml).
  - [x] Replace the build ecosystem with Vite, thereby removing Vue CLI (refer to [vitejs/plugin-vue2](https://github.com/vitejs/vite-plugin-vue2)).
  - [x] Replace `vue-cli-plugin-electron-builder`, which is no longer maintained, with a more reliable alternative such as Electron Forge, [vite-electron-builder](https://github.com/cawa-93/vite-electron-builder), or [`electron-vite`](https://github.com/alex8088/electron-vite) (seems to [support ESM](https://github.com/electron/electron/issues/21457#issuecomment-1537136292)), or `vite-plugin-electron` and `vite-plugin-electron-renderer`.

**Comment by undergroundwires** [comment]
Completed and released in [0.12.6](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.6) 🚀
