### ISSUE TITLE
Script Updates

### ISSUE THREAD

**Issue by Disk2019** [undergroundwires/privacy.sexy#26]
:: ----------------------------------------------------------
:: -----------------Ensure admin privileges------------------
:: ----------------------------------------------------------
REM  --> Run Batch File as Admin  Without Right Click
>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"  
REM --> If error flag set, we do not have admin.  
if '%errorlevel%' NEQ '0' (    echo Requesting administrative privileges...    goto UACPrompt) else ( goto gotAdmin )  
:UACPrompt  
echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"  
echo UAC.ShellExecute "%~s0", "", "", "runas", 1 >> "%temp%\getadmin.vbs"  
"%temp%\getadmin.vbs"  
exit /B
:gotAdmin
:: ----------------------------------------------------------

:: ----------------------------------------------------------
:: --------------------- Defender Settings ------------------
:: ----------------------------------------------------------
echo --- Defender Extra Settings
reg add "HKLM\Software\Policies\Microsoft\Windows Defender\MpEngine" /v "MpEnablePus" /t REG_DWORD /d "0" /f
reg add "HKLM\Software\Policies\Microsoft\Windows Defender\Real-Time Protection" /v "DisableBehaviorMonitoring" /t REG_DWORD /d "1" /f
reg add "HKLM\Software\Policies\Microsoft\Windows Defender\Real-Time Protection" /v "DisableIOAVProtection" /t REG_DWORD /d "1" /f
reg add "HKLM\Software\Policies\Microsoft\Windows Defender\Real-Time Protection" /v "DisableOnAccessProtection" /t REG_DWORD /d "1" /f
reg add "HKLM\Software\Policies\Microsoft\Windows Defender\Real-Time Protection" /v "DisableRoutinelyTakingAction" /t REG_DWORD /d "1" /f
reg add "HKLM\Software\Policies\Microsoft\Windows Defender\Real-Time Protection" /v "DisableScanOnRealtimeEnable" /t REG_DWORD /d "1" /f
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Reporting" /v "DisableGenericRePorts" /t REG_DWORD /d 1 /f
reg add "HKLM\Software\Policies\Microsoft\Windows Defender\Reporting" /v "DisableEnhancedNotifications" /t REG_DWORD /d "1" /f
reg add "HKLM\Software\Policies\Microsoft\Windows Defender\SpyNet" /v "DisableBlockAtFirstSeen" /t REG_DWORD /d "1" /f
reg add "HKLM\Software\Policies\Microsoft\Windows Defender\SpyNet" /v "SpynetReporting" /t REG_DWORD /d "0" /f
reg add "HKLM\Software\Policies\Microsoft\Windows Defender\SpyNet" /v "SubmitSamplesConsent" /t REG_DWORD /d "2" /f
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Spynet" /v "LocalSettingOverrideSpynetReporting" /t REG_DWORD /d 0 /f
reg add "HKLM\System\CurrentControlSet\Control\WMI\Autologger\DefenderApiLogger" /v "Start" /t REG_DWORD /d "0" /f
reg add "HKLM\System\CurrentControlSet\Control\WMI\Autologger\DefenderAuditLogger" /v "Start" /t REG_DWORD /d "0" /f
reg add "HKLM\SOFTWARE\Policies\Microsoft\MRT" /v "DontReportInfectionInformation" /t REG_DWORD /d 1 /f
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\System" /v "EnableSmartScreen" /t REG_DWORD /d 0 /f
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /v "SmartScreenEnabled" /t REG_SZ /d "Off" /f 
reg add "HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Explorer" /v "SmartScreenEnabled" /t REG_SZ /d "Off" /f 
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppHost" /v "EnableWebContentEvaluation" /t REG_DWORD /d 0 /f 
reg add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\AppHost" /v "EnableWebContentEvaluation" /t REG_DWORD /d 0 /f
reg add "HKLM\SOFTWARE\Policies\Microsoft\MRT" /v "DontOfferThroughWUAU" /t REG_DWORD /d 1 /f
reg add "HKLM\System\CurrentControlSet\Services\WdNisSvc" /v "Start" /t REG_DWORD /d "4" /f
echo. Add Hosts to Defender Exclusion
WMIC /NAMESPACE:\\root\Microsoft\Windows\Defender PATH MSFT_MpPreference call Add ExclusionPath="%Windir%\System32\drivers\etc\hosts"
:: ----------------------------------------------------------

:: ----------------------------------------------------------
:: ----- Remove DefaultUser0 Account For Privacy ------------
:: ----------------------------------------------------------
echo --- Remove DefaultUser0 Account For Privacy
net user defaultuser0 /delete
:: ----------------------------------------------------------

:: ----------------------------------------------------------
:: --------- Reset Defender Antimalware Platform ------------
:: ----------------------------------------------------------
echo --- Reset Defender Antimalware Platform
"%programfiles%\Windows Defender\MpCmdRun.exe" -resetplatform
:: ----------------------------------------------------------

:: ----------------------------------------------------------
:: ------------- TakeOwnership of WaasMedic -----------------
:: ----------------------------------------------------------
echo --- TakeOwnership of WaasMedic logs and Delete them
takeown /f %SystemRoot%\Logs\waasmedic /r /d y
icacls %SystemRoot%\Logs\waasmedic /grant administrators:F /t
rd /s /q %SystemRoot%\Logs\waasmedic
:: ----------------------------------------------------------

:: ----------------------------------------------------------
:: ------------- TakeOwnership of SystemApps ----------------
:: ----------------------------------------------------------
echo --- TakeOwnership of SystemApps and Delete extra found apps directories
takeown /f %SystemRoot%\SystemApps /r /d y
icacls %SystemRoot%\SystemApps /grant administrators:F /t
:: ----------------------------------------------------------

:: ----------------------------------------------------------
:: ------------ Set User TEMP to Windows TEMP ---------------
:: ----------------------------------------------------------
echo --- Setting User TEMP to Windows TEMP and Remove Onedrive User Variable
reg delete "HKCU\Environment" /v "OneDrive" /f
reg add "HKCU\Environment" /v "TEMP" /t REG_SZ /d "C:\Windows\Temp" /f
reg add "HKCU\Environment" /v "TMP" /t REG_SZ /d "C:\Windows\Temp" /f
:: ----------------------------------------------------------

Improved Ondrive Removal Part  with complete Leftovers Removal
:: ----------------------------------------------------------
:: -------------------- Remove OneDrive ---------------------
:: ----------------------------------------------------------
echo --- Remove OneDrive
taskkill /f /im OneDrive.exe
%SystemRoot%\System32\OneDriveSetup.exe /uninstall
%SystemRoot%\SysWOW64\OneDriveSetup.exe /uninstall
rd /S /Q "C:\OneDriveTemp"
rd /S /Q "%UserProfile%\OneDrive"
rd /S /Q "%LocalAppData%\Microsoft\OneDrive"
rd /S /Q "%ProgramData%\Microsoft OneDrive"
del /S /Q /F %AppData%\Microsoft\Windows\Start Menu\Programs\OneDrive.lnk"
reg delete "HKCR\CLSID{018D5C66-4533-4307-9B53-224DE2ED1FE6}" /f
reg delete "HKCR\Wow6432Node\CLSID{018D5C66-4533-4307-9B53-224DE2ED1FE6}" /f
reg delete "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" /v "OneDriveSetup" /f
reg add "HKLM\SOFTWARE\WOW6432Node\Policies\Microsoft\Windows\OneDrive" /v "DisableFileSyncNGSC" /t REG_DWORD /d "1" /f
reg add "HKCR\CLSID\{018D5C66-4533-4307-9B53-224DE2ED1FE6}" /v System.IsPinnedToNameSpaceTree /t REG_DWORD /d "0" /f
reg add "HKCR\Wow6432Node\CLSID\{018D5C66-4533-4307-9B53-224DE2ED1FE6}" /v System.IsPinnedToNameSpaceTree /t REG_DWORD /d "0" /f
:: ----------------------------------------------------------

Improved Clear logs to watch all logs getting cleared : Must be in Last of Script [mandatory]
:: ----------------------------------------------------------
:: ------------ Clear All Windows Event Logs ----------------
:: ----------------------------------------------------------
echo --- Clearing All Windows Event Logs
for /f "tokens=*" %%i in ('wevtutil.exe el') do echo "%%i" & wevtutil.exe cl "%%i" & wevtutil.exe cl System
echo --- Cleared All Windows Event Logs
taskkill /f /im Explorer.exe & start Explorer.exe
:: ----------------------------------------------------------

Thanks & Regards ,
Disk2019

**Comment by undergroundwires** [comment]
Hi @Disk2019 , and great to welcome you back and thanks again for your deep analysis of scripts and very constructive feedback.

They look great in the first look. I love the ideas, especially the one with prompting UAC. Great! I'll do more testing and look at them deeper and come with feedback.

**Comment by Disk2019** [comment]
Some of my Forensic Science Lab colleagues told me that capability removal is not working for them as they are on different build so i have done a little change ie removing capabilities via powershell command within the script via common name * .

script changes are as follows :

Powershell -Command "Get-WindowsCapability -Online | Where-Object { $_.CapabilityName -like 'App.StepsRecorder*' } | Remove-WindowsCapability -Online"
Powershell -Command "Get-WindowsCapability -Online | Where-Object { $_.CapabilityName -like 'App.Support.QuickAssist*' } | Remove-WindowsCapability -Online"
Powershell -Command "Get-WindowsCapability -Online | Where-Object { $_.CapabilityName -like 'Browser.InternetExplorer*' } | Remove-WindowsCapability -Online"
Powershell -Command "Get-WindowsCapability -Online | Where-Object { $_.CapabilityName -like 'Hello.Face*' } | Remove-WindowsCapability -Online"
Powershell -Command "Get-WindowsCapability -Online | Where-Object { $_.CapabilityName -like 'Language.Speech*' } | Remove-WindowsCapability -Online"
Powershell -Command "Get-WindowsCapability -Online | Where-Object { $_.CapabilityName -like 'Language.TextToSpeech*' } | Remove-WindowsCapability -Online"
Powershell -Command "Get-WindowsCapability -Online | Where-Object { $_.CapabilityName -like 'MathRecognizer*' } | Remove-WindowsCapability -Online"
Powershell -Command "Get-WindowsCapability -Online | Where-Object { $_.CapabilityName -like 'Media.WindowsMediaPlayer*' } | Remove-WindowsCapability -Online"
Powershell -Command "Get-WindowsCapability -Online | Where-Object { $_.CapabilityName -like 'Microsoft.Windows.PowerShell.ISE*' } | Remove-WindowsCapability -Online"
Powershell -Command "Get-WindowsCapability -Online | Where-Object { $_.CapabilityName -like 'OneCoreUAP.OneSync*' } | Remove-WindowsCapability -Online"
Powershell -Command "Get-WindowsCapability -Online | Where-Object { $_.CapabilityName -like 'OpenSSH.Client*' } | Remove-WindowsCapability -Online"
Powershell -Command "Get-WindowsCapability -Online | Where-Object { $_.CapabilityName -like 'OpenSSH.Server*' } | Remove-WindowsCapability -Online"
Powershell -Command "Get-WindowsCapability -Online | Where-Object { $_.CapabilityName -like 'Print.Fax.Scan*' } | Remove-WindowsCapability -Online"
Powershell -Command "Get-WindowsCapability -Online | Where-Object { $_.CapabilityName -like 'Print.Management.Console*' } | Remove-WindowsCapability -Online"

after this if a user is on any build of Win10 it will remove the capabilities via common name * but not as we have done it previously via dism  capabilities removal.

Thanks & Regards
Disk2019

**Comment by undergroundwires** [comment]
Very smart. Thanks again and for your friends for making Windows better for everyone 👏 You have been super helpful ensuring good quality everywhere. Btw I also improved OneDrive when you were gone.. Very hard to get rid of it..

If you have more requests please create new issues so we can track progress cleanly and keep this issue for the scripts already mentioned only.

I also started added revert scripts for more and more tweaks after your feedback. And I'd like to add every new tweak with their revert scripts, it'd speed up things a lot for me if you'd have time to add scripts to revert each script as well.

Just keeping a checklist here to keep you updated with the status, I'll check the boxes as they are addedand leave a comment when everything is released.

**TODO**
- [ ] Ensure admin privileges
- [ ] Defender Settings
- [ ] Remove DefaultUser0 Account For Privacy
- [ ] Reset Defender Antimalware Platform
- [ ] TakeOwnership of WaasMedic
- [ ] TakeOwnership of SystemApps
- [ ] Set User TEMP to Windows TEMP
- [ ] Remove OneDrive
- [ ] Clear All Windows Event Logs
- [ ] Uninstall apps fix

**Comment by undergroundwires** [comment]
Very smart. Thanks again and for your friends for making Windows better for everyone 👏 You have been super helpful ensuring good quality everywhere. Btw I also improved OneDrive when you were gone.. Very hard to get rid of it..

Let's work with scripts already mentioned in this issue and create new issues for new stuff. This way we can have discussions more clearly and track the work easily 😎

I also started added revert scripts for more and more tweaks after your feedback. And I'd like to add every new tweak with their revert scripts, it'd speed up things a lot for me if you'd have time to add scripts to revert each script as well.

Just keeping a checklist here to keep you updated with the status, I'll check the boxes as they are addedand leave a comment when everything is released.

**TODO**
- [ ] Ensure admin privileges
- [ ] Defender Settings
- [ ] Remove DefaultUser0 Account For Privacy
- [ ] Reset Defender Antimalware Platform
- [ ] TakeOwnership of WaasMedic
- [ ] TakeOwnership of SystemApps
- [ ] Set User TEMP to Windows TEMP
- [ ] Remove OneDrive
- [ ] Clear All Windows Event Logs
- [ ] Uninstall apps fix

**Comment by Disk2019** [comment]
Please Remove Wordpad , Notepad & M$Paint from Removal Categories as many users use them . some of my FSL colleagues told me that these removal options must not be there as default checked if a user who is unknown of project will start with direct all options checked on the script at your script generation domain which is privacy.sexy .
mostly users are not aware what the script is doing & they just execute it directly without acknowledging the results thats why we must not add any common windows capability into project which is mostly used by users as three of these capabilities Wordpad , Notepad & Paint i told you are most common used windows app.

**Comment by undergroundwires** [comment]
> Wordpad, Notepad & M$Paint

They are not there checked in "Recommended" mode but yes they get deleted on "All" mode. They are not privacy intrusive (as I know) and not bloatware (as many would think). I'll consider removing them. 

Have fun working with security. It's my hobby as well 👍 I'd like to see other robocops as contributors as well. It's not a security breach to that but it's only good to share your knowledge to help the community and nation to become more secure 👍

**Comment by Disk2019** [comment]
thanks for this consideration . I am always happy to work for a good kind hearted person who care for suggestions & requests. any way we can get in touch without this github option so that i will request you everything there . i hope you will get my POV easily now as everything is said in clear words in my previous comment which is deleted by myself for anonymity reason.

**Comment by Disk2019** [comment]
Pardone Please : Some of my friends told me that the code to remove capabilities is not showing any operation on there display hence i have done some changes to it so that users will see whats going on via the capabilities removal script.

Code As Follows :

echo ==========================================================
echo ------------------Remove Capabilities---------------------
echo ==========================================================
echo --- Removing Steps Recorder Capability
Powershell -Command "Get-WindowsCapability -Online -Name "App.StepsRecorder*" | Remove-WindowsCapability -Online"
echo --- Removing Support Quick Assist Capability
Powershell -Command "Get-WindowsCapability -Online -Name "App.Support.QuickAssist*" | Remove-WindowsCapability -Online"
echo --- Removing Internet Explorer Capability
Powershell -Command "Get-WindowsCapability -Online -Name "Browser.InternetExplorer*" | Remove-WindowsCapability -Online"
echo --- Removing Hello Face Capability
Powershell -Command "Get-WindowsCapability -Online -Name "Hello.Face*" | Remove-WindowsCapability -Online"
echo --- Removing Language Speech Capability
Powershell -Command "Get-WindowsCapability -Online -Name "Language.Speech*" | Remove-WindowsCapability -Online"
echo --- Removing Language Text To Speech Capability
Powershell -Command "Get-WindowsCapability -Online -Name "Language.TextToSpeech*" | Remove-WindowsCapability -Online"
echo --- Removing Math Recognizer Capability
Powershell -Command "Get-WindowsCapability -Online -Name "MathRecognizer*" | Remove-WindowsCapability -Online"
echo --- Removing Windows Media Player Capability
Powershell -Command "Get-WindowsCapability -Online -Name "Media.WindowsMediaPlayer*" | Remove-WindowsCapability -Online"
echo --- Removing Powershell ISE Capability
Powershell -Command "Get-WindowsCapability -Online -Name "Microsoft.Windows.PowerShell.ISE*" | Remove-WindowsCapability -Online"
echo --- Removing OneDrive OneSync Capability
Powershell -Command "Get-WindowsCapability -Online -Name "OneCoreUAP.OneSync*" | Remove-WindowsCapability -Online"
echo --- Removing Open SSH Client Capability
Powershell -Command "Get-WindowsCapability -Online -Name "OpenSSH.Client*" | Remove-WindowsCapability -Online"
echo --- Removing Open SSH Server Capability
Powershell -Command "Get-WindowsCapability -Online -Name "OpenSSH.Server*" | Remove-WindowsCapability -Online"
echo --- Removing Print Fax Scan Capability
Powershell -Command "Get-WindowsCapability -Online -Name "Print.Fax.Scan*" | Remove-WindowsCapability -Online"
echo --- Removing Print Management Console Capability
Powershell -Command "Get-WindowsCapability -Online -Name "Print.Management.Console*" | Remove-WindowsCapability -Online"
echo --- Clearing Assigned Access
Powershell -Command "Clear-AssignedAccess"
echo --- Removed All Capabilities
echo --- Saving Capabilities Current State After Removal as Text File on Your Desktop
Powershell -Command "Get-WindowsCapability -Online | Select Name , State >%UserProfile%\Desktop\Capabilities.txt"
echo ==========================================================

**Comment by undergroundwires** [comment]
Hi,

Thanks again for stabilizing this library! Your POV is an absolutely perfect use-case for making stuff better here. Social media policies are made for non-technical people generally, not fr people who knows what they're doing.. But I understand it, and thanks for risking it to make everyones OS more secure and private.

I had time to look much deeper into the scripts. I improved those with "👍" emoji, restructured scripts and added many revert options and here's my feedback:

- 👍 Remove OneDrive 
	- Awesome additions.
	- Btw you have typo "\" should be there after CLSID
	- Added with some nice categoration and documentation
- 👍 Ensure admin privileges
	- This is one of the best ones 😎
	- Very well thought and thanks 🙏 and virtual stars for you ⭐⭐⭐
	- Refactored little bit and added it.
- 👍 TakeOwnership of WaasMedic
	- Smart.
	- Thanks for testing!
- 👍 Remove "Wordpad, Notepad & M$Paint" from "Uninstall apps"
	- I decided to do that. Thanks!
- 👍 Uninstall fixes
	- Added with options to revert them.
- 🤔 Clear All Windows Event Logs
	- Good idea, make totally sense.
	- But script ordering is not supported yet.
		- a property `position: last` could be implemented for scripts.
		- no promises made but I might look at it in future (not close)
			- have some plans regarding GUI, documentation improvements and maybe adding macOS support before that.
		- otherwise it's just to implement it and send a pull request :)
- ❓ `DefaultUser0` seems like an old Windows bug that's been patched.
	- I don't think that we should fix bugs here, but if you think that it's somehow related to privacy to delete it, why?
	- https://superuser.com/questions/1152792/what-is-defaultuser0-and-is-it-safe-to-delete
- ❓ Reset Defender Antimalware Platform
	- "%ProgramFiles%\Windows Defender\MpCmdRun.exe" -resetplatform
	- Question: Why is it done, what do we achieve by this rollback?
		- Documented here: https://support.microsoft.com/en-us/help/4052623/update-for-microsoft-defender-antimalware-platform
- ❓ Set User TEMP to Windows TEMP 
	- OneDrive does not create any registry entry in "HKCU\Environment" when I tested.
		- Is this a documented behavior?
		- Did you observe any value there yourself
	- I really like to the idea of changin the TEMP folder. It's a nice sysops command but we should keep privacy-related stuff here otherwise it's going to get unmaintanable if we do too much.
- ❓ TakeOwnership of SystemApps
	- What's the point of this?
	- It only takes ownership, does not delete anything?
- ❓ Defender Settings
	- I understand your POV but think privacy.sexy as something that our grandmothers will use to increase privacy 😂
	- In this library (privacy.sexy) we should only focus on stuff that **increases** security or **stops** data-collection
	- We should not decrease security by disabling non-data collection services.
	- If we configure Windows Defender as you suggested then it loses almost all of its functions so users have option to delete it completely in this case.
	- The following I felt like are telemetry-free security improvements that shouldn't be disabled:
		- `MpEnablePus, `DisableBehaviorMonitoring`, `DisableIOAVProtection` , `DisableOnAccessProtection`, `DisableRoutinelyTakingAction`, `DisableScanOnRealtimeEnable`, `DisableEnhancedNotifications`, `DefenderApiLogger`, `DefenderAuditLogger`, `DisableBlockAtFirstSeen`
	- I might be wrong here. Open for your opinions about if they increase privacy.
	
Again, I love working with you and thanks again for everything. I'm sure you've been helpful to many people so far, an anonymous hero in the community 😊

P.S. When I was writing this, got a warning from OneDrive.. Painful to get rid of it. Maybe I'll be able to after your updates.

**Comment by undergroundwires** [comment]
You can find me (and my e-mail) at [my personal website](https://erkinekici.com). Feel free to take future stuff from there if you feel more comfortable.

**Comment by Disk2019** [comment]
❓ DefaultUser0 seems like an old Windows bug that's been patched.
I don't think that we should fix bugs here, but if you think that it's somehow related to privacy to delete it, why?
https://superuser.com/questions/1152792/what-is-defaultuser0-and-is-it-safe-to-delete

**Answer : If somebody is on LTSC 2019 then DefaultUser0 Account is by default created on Installation as telemetry account.
Hence it must be removed . if by default this account is not found on other builds of win10 then it will not affect any functionality of OS & will ignore it,**

❓ Reset Defender Antimalware Platform
"%ProgramFiles%\Windows Defender\MpCmdRun.exe" -resetplatform
Question: Why is it done, what do we achieve by this rollback?
Documented here: https://support.microsoft.com/en-us/help/4052623/update-for-microsoft-defender-antimalware-platform

Answer : Yes Not related to User Privacy but i found it useful for me in many Points cant discuss it though. Please do ignore it but it will not trouble any user in there OS functionality . Might add it in extra option not recommended . some in depth users of win10 will still found it useful according to there POV.

❓ Set User TEMP to Windows TEMP
OneDrive does not create any registry entry in "HKCU\Environment" when I tested.
Is this a documented behavior?
Did you observe any value there yourself
I really like to the idea of changing the TEMP folder. It's a nice sysops command but we should keep privacy-related stuff here otherwise it's going to get un maintainable if we do too much.

Answer : [Changing TEMP & TMP user Variable to Win TemP] Yes Not related to User Privacy but useful for in depth users of Win10 OS cant discuss it though. 
Onedrive Variable Removal : please have a look at win10 2004 19041.450 build iso updated by M$ some days ago on MSDN. it is having this User Env Variable in that registry.

❓ TakeOwnership of SystemApps
What's the point of this?
It only takes ownership, does not delete anything?

Answer : Yes it is not deleting any systemapps directory but only to take ownership of same directory cuz i don't want any user to get into any trouble thereafter . Users are free thereafter taking ownership of whole systemapps directory to choose the system apps directly they don't want to use & rename them to .backup after origin name so that they can easily take back those apps directory to default via renaming it again to the same state as it was at a time of urgent need when WU will throw error to them installing updates because Win10 is moving to a different state & as one time will come it will be totally M$ APP based OS.

❓ Defender Settings
I understand your POV but think privacy.sexy as something that our grandmothers will use to increase privacy 😂
In this library (privacy.sexy) we should only focus on stuff that increases security or stops data-collection
We should not decrease security by disabling non-data collection services.
If we configure Windows Defender as you suggested then it loses almost all of its functions so users have option to delete it completely in this case.
The following I felt like are telemetry-free security improvements that shouldn't be disabled:
MpEnablePus, DisableBehaviorMonitoring, DisableIOAVProtection,DisableOnAccessProtection, DisableRoutinelyTakingAction, DisableScanOnRealtimeEnable, DisableEnhancedNotifications, DefenderApiLogger, DefenderAuditLogger, DisableBlockAtFirstSeen`
I might be wrong here. Open for your opinions about if they increase privacy.

Answer : Yes i agree with you on this point . but in a scenario if user don't want to use defender as there default OS AV & want to install third party Security App with a Stateful Firewall then these tweaks will show him/her whats the use of them. please do ignore them if you found it irrelevant to the Script Project.
After M$ has updated defender Antimalware Platform to 4.18.2007.8 it becomes very difficult for users to disable defender completely & one time will come again i say defender cant be tweaked from Win10 Operating system as M$ is completely moving its win10 state to a M$ App based OS.

Right now Configure Defender by Andyfull & Defender Control by Sordum is only working for win10 Defender Tweak.

Thanks & Regards,
Disk2019

**Comment by undergroundwires** [comment]
- DefaultUser0: `DefaultUser0` tweak is added in privacy cleanup.
- OneDrive: `reg delete "HKCU\Environment" /v "OneDrive" /f` is added.
- Defender settings: Argument that it's hard to get rid of it sounds logical. Script are added under removal of defender.

Excluded those two:
-  `"%ProgramFiles%\Windows Defender\MpCmdRun.exe" -resetplatform`: 
- `Set User TEMP to Windows TEMP`

So everything else is included except those two. I also documented them and even added more stuff 🌟. I'll release them along with some GUI improvements hopefully this week.

**Comment by undergroundwires** [comment]
After your explanations, I added those:

- DefaultUser0: `DefaultUser0` tweak is added in privacy cleanup.
- OneDrive: `reg delete "HKCU\Environment" /v "OneDrive" /f` is added.
- Defender settings: Argument that it's hard to get rid of it sounds logical. Script are added under removal of defender.

Excluded those two:
-  `"%ProgramFiles%\Windows Defender\MpCmdRun.exe" -resetplatform`: 
- `Set User TEMP to Windows TEMP`

So everything else is included except those two. I also documented them and even added more stuff 🌟. I'll release them along with some GUI improvements hopefully this week.

Big thank you again!

**Comment by undergroundwires** [comment]
After your explanations, I added those:

- DefaultUser0: `DefaultUser0` tweak is added in privacy cleanup.
- OneDrive: `reg delete "HKCU\Environment" /v "OneDrive" /f` is added.
- Defender settings: Argument that it's hard to get rid of it sounds logical. Script are added under removal of defender.

They're probably good sysops command but excluded those two as I could not understand the point:
-  `"%ProgramFiles%\Windows Defender\MpCmdRun.exe" -resetplatform`: 
- `Set User TEMP to Windows TEMP`

So everything else is included except those two. I also documented them and even added more stuff 🌟. I'll release them along with some GUI improvements hopefully this week.

Big thank you again!

**Comment by Disk2019** [comment]
Big Thanks to you for creating such an awesome win10 privacy project . its more then awesome.

**Comment by Disk2019** [comment]
Block CCleaner & Malwarebytes Calling Home for Telemetry

echo ==================================================
echo ----- Block CCleaner Calling Home Via hosts ------
echo ==================================================
::Block IPv4 CCleaner Calling Home 100% Working by Anon Ops India
echo 127.0.0.1 avast.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 www.avast.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 ccleaner.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 www.ccleaner.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 piriform.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 www.piriform.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 verify.ccleaner.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 license.piriform.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 emupdate.avcdn.net >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 ccleaner.tools.avcdn.net >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 analytics.ff.avast.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 shepherd.ff.avast.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 ip-info.ff.avast.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 service.piriform.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 updates.ccleaner.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 ipm-provider.ff.avast.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 ncc.avast.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 ncc.avast.com.edgesuite.net >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 alpha-crap-stage.ff.avast.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 alpha-license-dealer-stage.ff.avast.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 softwareupdatechecker.live-everest-media.net >> %WinDir%\system32\drivers\etc\hosts
echo ==================================================

echo ==================================================
echo --- Block CCleaner IPv6 Calling Home Via hosts ---
echo ==================================================
::Block IPv6 CCleaner Calling Home 100% Working by Anon Ops India
echo ::1 avast.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 www.avast.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 ccleaner.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 www.ccleaner.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 piriform.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 www.piriform.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 verify.ccleaner.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 license.piriform.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 emupdate.avcdn.net >> %WinDir%\system32\drivers\etc\hosts
echo ::1 ccleaner.tools.avcdn.net >> %WinDir%\system32\drivers\etc\hosts
echo ::1 analytics.ff.avast.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 shepherd.ff.avast.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 ip-info.ff.avast.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 service.piriform.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 updates.ccleaner.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 ipm-provider.ff.avast.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 ncc.avast.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 ncc.avast.com.edgesuite.net >> %WinDir%\system32\drivers\etc\hosts
echo ::1 alpha-crap-stage.ff.avast.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 alpha-license-dealer-stage.ff.avast.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 softwareupdatechecker.live-everest-media.net >> %WinDir%\system32\drivers\etc\hosts
echo ==================================================

echo ==================================================
echo --- Block Malwarebytes Calling Home Via hosts ----
echo ==================================================
::Block IPv4 Malwarebytes Calling Home 100% Working by Anon Ops India
echo 127.0.0.1 iris.mwbsys.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 links.malwarebytes.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 my-device.malwarebytes.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 sirius.mwbsys.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 keystone.mwbsys.com >> %WinDir%\system32\drivers\etc\hosts
echo 127.0.0.1 telemetry.malwarebytes.com >> %WinDir%\system32\drivers\etc\hosts

echo ==================================================
echo - Block Malwarebytes IPv6 Calling Home Via hosts -
echo ==================================================
::Block IPv6 Malwarebytes Calling Home 100% Working by Anon Ops India
echo ::1 iris.mwbsys.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 links.malwarebytes.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 my-device.malwarebytes.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 sirius.mwbsys.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 keystone.mwbsys.com >> %WinDir%\system32\drivers\etc\hosts
echo ::1 telemetry.malwarebytes.com >> %WinDir%\system32\drivers\etc\hosts
echo ==================================================

echo ==================================================
eco ---------- Apply Changes to Hosts File ------------
echo ==================================================
:: Apply Changes to System Hosts File Immediately
ipconfig /flushdns
echo ==================================================

Thanks & Regards
Disk2019

**Comment by undergroundwires** [comment]
@Disk2019 thanks for following the development, some small touches left and I'll release them. Host file editing was something I was considering but did not have time to add.. I agree that we should add them as well. However there are two issues we should consider:
1. Re-running the script should be safe. If we always add to hosts file then we create duplicate lines. To avoid this we need to search for a line and add the rule only if it does not exist.
2. We should also a way to to revert the changes e.g. check if rule exists in hosts file and delete it.

**Comment by Disk2019** [comment]
we can use [if] command function to cross check whether entry is already there or not.

**Comment by undergroundwires** [comment]
Good idea. A oneliner would be great as we'll repeat this many times. Also we could use the same `if` to delete the entries.

One other challenge is the maintenance of the domains. Actively maintaining those and ensuring that they don't break stuff and are up-to-date is very time consuming and should not be the core focus for us. Maybe we can use a third party list such as https://github.com/supmaxi/Bad-IP-s . However privacy.sexy works with parsing a single yaml file so a custom logic will be required to be able to work with another text file to get the information, and it introduces a new level of complexity. I guess we should start with hardcoding important ones at first and then can consider having a third party list.

**Comment by undergroundwires** [comment]
Another alternative is to download and use https://github.com/crazy-max/WindowsSpyBlocker through a script.

**Comment by undergroundwires** [comment]
Released as part of [0.13.0](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.0) 🚀.
